apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-multi-app-deploy
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: test
                  server: https://kubernetes.default.svc
          - list:
              elements:
                - name: v1
                  repoPath: helm-chart/nginx
                  namespace: test
                - name: v2
                  repoPath: helm-chart/nginx
                  namespace: test
    
  template:
    metadata:
      name: "{{name}}-{{environment}}"
    spec:
      project: poc-jobs
      source:
        repoURL: https://github.com/nking-betika/gitops-poc.git
        path: "{{repoPath}}"
        targetRevision: HEAD
        helm:
          valueFiles:
            - "values-{{name}}.yaml"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true